import { Building } from "@/store/gameStore";

export const BUILDINGS: Building[] = [
  {
    id: "soc",
    name: "SOC Headquarters",
    subtitle: "Security Operations Center",
    color: "#00ff88",
    icon: "Shield",
    position: [-8, 0, -6],
    size: [3, 8, 3],
    floors: [
      { title: "Command Center", content: "Real-time monitoring of all global cyber threats. AI-powered threat detection operating at 99.97% accuracy." },
      { title: "Incident Response", content: "24/7 incident response team handling 10,000+ alerts daily. Average response time: 47 seconds." },
      { title: "Threat Hunting", content: "Proactive threat hunting operations across 180+ countries. Zero-day detection rate: 94.2%." },
      { title: "Analytics", content: "Advanced behavioral analytics processing 2.4PB of threat data daily." },
    ],
  },
  {
    id: "portfolio",
    name: "Portfolio Tower",
    subtitle: "Developer Showcase",
    color: "#00d4ff",
    icon: "User",
    position: [0, 0, 0],
    size: [2.5, 10, 2.5],
    floors: [
      { title: "About Me", content: "Cybersecurity Engineer & Full-Stack Developer. Passionate about building secure systems and fighting cybercrime." },
      { title: "Skills", content: "Python, JavaScript, TypeScript, React, Node.js, Three.js, Docker, Kali Linux, Wireshark, Metasploit, Nmap." },
      { title: "Projects", content: "Android Malware Detector - ML-powered malware detection for Android devices. NetSentinel - Network intrusion detection system." },
      { title: "Experience", content: "Cybersecurity Analyst intern at TechCorp. CTF Champion. Bug Bounty Hunter. Open Source Contributor." },
      { title: "Education", content: "B.Tech in Computer Science with specialization in Cybersecurity." },
      { title: "Achievements", content: "Top 1% on TryHackMe. DEF CON qualifier. Published research on Android malware analysis." },
      { title: "Resume", content: "Download resume and view detailed career history." },
      { title: "Contact", content: "Ready to collaborate on cybersecurity projects. Let's connect!" },
    ],
  },
  {
    id: "malware-lab",
    name: "Malware Research Lab",
    subtitle: "Malware Analysis & Reverse Engineering",
    color: "#ff0040",
    icon: "Bug",
    position: [-8, 0, 4],
    size: [3, 7, 3],
    floors: [
      { title: "Analysis Chamber", content: "Advanced malware sandbox analyzing 50,000+ samples daily. Custom detonation environments." },
      { title: "Reverse Engineering", content: "Static and dynamic analysis labs with IDA Pro, Ghidra, and custom toolchains." },
      { title: "Virus Database", content: "Comprehensive malware family taxonomy with 12M+ signatures." },
    ],
  },
  {
    id: "darkweb-center",
    name: "Dark Web Intelligence",
    subtitle: "Darknet Monitoring & Analysis",
    color: "#8b00ff",
    icon: "Eye",
    position: [8, 0, -6],
    size: [3, 6, 3],
    floors: [
      { title: "Monitoring Station", content: "Continuous darknet surveillance across 47 markets and 200+ forums." },
      { title: "Threat Actors", content: "Tracking 2,847 active threat actor groups with AI-powered attribution." },
    ],
  },
  {
    id: "threat-intel",
    name: "Threat Intelligence Tower",
    subtitle: "Global Threat Intelligence",
    color: "#ff8800",
    icon: "Radar",
    position: [8, 0, 4],
    size: [3, 9, 3],
    floors: [
      { title: "Intelligence Hub", content: "Aggregating IOCs from 500+ sources. Real-time STIX/TAXII feeds." },
      { title: "Predictive Analytics", content: "AI models predicting emerging threats with 89% accuracy." },
      { title: "Geopolitical Analysis", content: "State-sponsored threat tracking across 195 nations." },
    ],
  },
  {
    id: "network-ops",
    name: "Network Operations",
    subtitle: "Network Defense & Monitoring",
    color: "#00ffcc",
    icon: "Network",
    position: [-4, 0, -10],
    size: [3, 6, 3],
    floors: [
      { title: "NOC Center", content: "Monitoring 10M+ network packets per second across global infrastructure." },
      { title: "Firewall Matrix", content: "Next-gen firewall management blocking 4.2B threats monthly." },
    ],
  },
  {
    id: "cloud-security",
    name: "Cloud Security District",
    subtitle: "Cloud Infrastructure Protection",
    color: "#4488ff",
    icon: "Cloud",
    position: [4, 0, -10],
    size: [3, 7, 3],
    floors: [
      { title: "Cloud Guardian", content: "Protecting 12,000+ cloud instances across AWS, Azure, and GCP." },
      { title: "Container Security", content: "Scanning 85,000+ containers daily with zero-trust architecture." },
    ],
  },
  {
    id: "forensics",
    name: "Digital Forensics Center",
    subtitle: "Cyber Forensics Investigation",
    color: "#ff4488",
    icon: "Search",
    position: [-12, 0, 0],
    size: [2.5, 5, 2.5],
    floors: [
      { title: "Forensics Lab", content: "Advanced digital forensics toolkit for evidence recovery and chain of custody." },
      { title: "Memory Analysis", content: "Volatility-powered memory forensics for live incident investigation." },
    ],
  },
  {
    id: "red-team",
    name: "Red Team Arena",
    subtitle: "Offensive Security Operations",
    color: "#ff2200",
    icon: "Sword",
    position: [12, 0, 0],
    size: [2.5, 5, 2.5],
    floors: [
      { title: "Attack Range", content: "Customized attack simulations with 500+ exploit frameworks." },
      { title: "Social Engineering", content: "Phishing simulation platform with AI-generated campaigns." },
    ],
  },
  {
    id: "blue-team",
    name: "Blue Team Academy",
    subtitle: "Defensive Security Training",
    color: "#2244ff",
    icon: "ShieldCheck",
    position: [-4, 0, 10],
    size: [3, 6, 3],
    floors: [
      { title: "Defense Training", content: "Hands-on defensive security training with real-world scenarios." },
      { title: "Playbook Library", content: "10,000+ incident response playbooks and automation scripts." },
    ],
  },
  {
    id: "cert-museum",
    name: "Certification Museum",
    subtitle: "Cybersecurity Certifications",
    color: "#ffcc00",
    icon: "Award",
    position: [4, 0, 10],
    size: [2.5, 5, 2.5],
    floors: [
      { title: "Hall of Certifications", content: "CEH, OSCP, CISSP, CompTIA Security+ and 100+ more certifications." },
    ],
  },
  {
    id: "innovation",
    name: "Project Innovation",
    subtitle: "R&D and Innovation Lab",
    color: "#00ff44",
    icon: "Lightbulb",
    position: [-12, 0, 8],
    size: [2.5, 5, 2.5],
    floors: [
      { title: "Innovation Lab", content: "Cutting-edge cybersecurity research and prototype development." },
    ],
  },
  {
    id: "mission-control",
    name: "Mission Control",
    subtitle: "Mission Management Center",
    color: "#ff0088",
    icon: "Target",
    position: [12, 0, -8],
    size: [2.5, 5, 2.5],
    floors: [
      { title: "Operations Floor", content: "Coordinating 1,200+ active cybersecurity missions globally." },
    ],
  },
  {
    id: "training",
    name: "Training Academy",
    subtitle: "Cybersecurity Learning",
    color: "#44ffaa",
    icon: "GraduationCap",
    position: [-8, 0, -12],
    size: [2.5, 4, 2.5],
    floors: [
      { title: "Classrooms", content: "Interactive cybersecurity courses from beginner to expert." },
    ],
  },
  {
    id: "comms",
    name: "Communication Hub",
    subtitle: "Encrypted Communications",
    color: "#ffaa44",
    icon: "Radio",
    position: [8, 0, 12],
    size: [2.5, 4, 2.5],
    floors: [
      { title: "Secure Channel", content: "Military-grade encrypted communication infrastructure." },
    ],
  },
  {
    id: "satellite",
    name: "Satellite Command",
    subtitle: "Satellite Cyber Operations",
    color: "#aa88ff",
    icon: "Satellite",
    position: [0, 0, -14],
    size: [2.5, 4, 2.5],
    floors: [
      { title: "Ground Station", content: "Controlling 47 cybersecurity satellites for global monitoring." },
    ],
  },
  {
    id: "quantum-center",
    name: "Quantum Data Center",
    subtitle: "Quantum Computing Hub",
    color: "#00aaff",
    icon: "Atom",
    position: [0, 0, 14],
    size: [2.5, 4, 2.5],
    floors: [
      { title: "Quantum Core", content: "512-qubit quantum processor for cryptographic analysis." },
    ],
  },
];

export const CYBER_STATS = {
  attacksBlocked: 1_847_293,
  threatsNeutralized: 42_891,
  uptime: 99.97,
  countriesProtected: 195,
  activeAnalysts: 12_847,
  networksMonitored: 2_400_000,
};

export const MISSIONS = [
  {
    id: "ransomware-001",
    title: "Operation: Lockdown",
    description: "Stop a ransomware attack targeting hospital networks",
    difficulty: "HIGH",
    reward: "2500 XP",
    status: "ACTIVE",
  },
  {
    id: "phishing-002",
    title: "Phish Hunt",
    description: "Investigate a sophisticated phishing campaign",
    difficulty: "MEDIUM",
    reward: "1500 XP",
    status: "ACTIVE",
  },
  {
    id: "ddos-003",
    title: "DDoS Shield",
    description: "Protect critical infrastructure from DDoS attack",
    difficulty: "EXTREME",
    reward: "5000 XP",
    status: "LOCKED",
  },
  {
    id: "malware-004",
    title: "Virus Hunter",
    description: "Find and neutralize a zero-day malware sample",
    difficulty: "HIGH",
    reward: "3000 XP",
    status: "ACTIVE",
  },
  {
    id: "forensics-005",
    title: "Digital Detective",
    description: "Analyze logs to trace an advanced persistent threat",
    difficulty: "MEDIUM",
    reward: "2000 XP",
    status: "COMPLETED",
  },
];

export const COLORS = {
  neonGreen: "#00ff88",
  neonBlue: "#00d4ff",
  neonCyan: "#00ffcc",
  neonPurple: "#8b00ff",
  neonPink: "#ff0088",
  neonOrange: "#ff8800",
  neonRed: "#ff0040",
  neonYellow: "#ffcc00",
  darkBg: "#0a0a0f",
  panelBg: "rgba(10, 10, 20, 0.85)",
  gridLine: "rgba(0, 255, 136, 0.1)",
};
